#!/usr/bin/env perl

use strict;
use warnings;

my @test_files;

if (-d 't/') {
    $ENV{PERL5LIB}='./lib';
    @test_files = (<t/*.t>);
}
else {
    $ENV{PERL5LIB}='../lib';
    @test_files = (<*.t>);
}

use TAP::Harness;
my $harness = TAP::Harness->new();
$harness->runtests(@test_files);
